[versions]
androidGradlePlugin = "8.1.2"
appcompat = "1.6.1"
coreKtx = "1.12.0"
detektPlugin = "1.18.1"
espressoCore = "3.5.1"
junit = "4.13.2"
junitVersion = "1.1.5"
kotlinAndroidPlugin = "1.9.10"
kotlinParcelize = "1.6.0-M1"
ktlintPlugin = "11.6.1"
kotlinSerialization = "2.3.7"
kotlinSerializationPlugin = "1.9.10"
ktor = "2.3.7"
# Latest version (1.4.11) of logback causes crashes: https://youtrack.jetbrains.com/issue/KTOR-5227
logback = "1.2.11"
material = "1.11.0"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
junit = { module = "junit:junit", version.ref = "junit" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "kotlinSerialization" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[plugins]
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektPlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroidPlugin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlinAndroidPlugin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlinParcelize" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerializationPlugin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintPlugin" }