name: On Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  onPullRequestJob:
    name: Verify code base when pull request is published/updated
    runs-on: ubuntu-latest

    steps:
      - name: Run checkout github action
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # pin@v4
        with:
          lfs: 'true'
          fetch-depth: 0

      - name: Detect Arch
        id: detect-arch
        uses: ./config/actions/detect-arch

      - name: Setup GitHub Runner workflow
        uses: ./config/actions/setup-runner

      - name: Get latest tag
        id: latest-tag
        uses: ./config/actions/get-latest-tag
        with:
          pattern: 'v*'

      - name: Generate version code
        id: version-code
        uses: ./config/actions/generate-version-code

      - name: Generate version name
        id: version-name
        uses: ./config/actions/version-name
        with:
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.latest-tag.outputs.current-tag }}

      - name: Run gradle unit tests
        uses: ./config/actions/gradle-check
        with:
          version-code: ${{ steps.version-code.outputs.version-code }}
          version-name: ${{ steps.version-name.outputs.version-name }}

      - name: Run sonar analysis
        uses: ./config/actions/sonar-analysis
        with:
          project-version: ${{ steps.version-name.outputs.version-name }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@d304d050d930b02a896b0f85935344f023928496 # pin@v1.1.0
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          scanMetadataReportFile: ${{ github.workspace }}/build/sonar/report-task.txt

      - name: Bundle reports folder
        uses: ./config/actions/bundle-reports
